### ISSUE TITLE
Make sure that SSH deployment works well in Field Manager

### ISSUE THREAD

**Issue by hekonsek** [things8/zed#93]
@ajurasz Create Zed ticket - for the reference.

**Comment by hekonsek** [comment]
@ajurasz Any updates on this? :) I'm asking because I'm working on the Fabric8/Kubernetes/OpenShift based backend for our IoT toys and I'd like to create configuration management service and use our UI to  send updated configuration to the application we previously deployed.

**Comment by ajurasz** [comment]
@hekonsek I should have the fix for Wednesday.

**Comment by ajurasz** [comment]
Fix in the zed was minor (I just added flag which indicate if execude mkdirs on remote host because pi user in rapbian os has no permission to do this)

**Comment by hekonsek** [comment]
Yay! Great. Thanks for handling this. I'm polishing Message Store Service (together with some Hawt.io based UI). That would make great demo all together :) .
